### ISSUE TITLE
Cannot setup payara server

### ISSUE THREAD

**Issue by zliu13286** [payara/ecosystem-support#1]
VScode: 1.53.1 on MacOS Big Sur.
Payara 5.2

Always stuck at step 4: select an exist domain. I can't select domain1 and can't go through, also tried with add new domain, also not working.

**Comment by vgjokaj** [comment]
I have the same problem using VS Code 1.54.3 and Payara 5.2021.1 in Ubuntu 20.04.

**Comment by MeroRai** [comment]
Hi, I was able to successfully register Payara Server in VS Code 1.54,3 using Payara Server 5.2021 in Windows 10. Just make sure when you are selecting the Payara Server location, the directory structure is as the following: `$YOUR_PAYARA_INSTALLTION/payara5`.

**Comment by vgjokaj** [comment]
Hi @MeroRai. I selected the right location "$PAYRA_INSTALLATION/payara5", otherwise if I select a wrong directory, then I get the following error in VS Code "Selected Payara Server path is invalid.".

**Comment by rgrashel** [comment]
Did anybody get this to work?  I get this same thing on Amazon Linux 2.  Choose the directory and then on step 4/4 go to choose domain1 and it won't select it and the plus button won't function.  The server entry can't be created.  I'm not sure why this issue is closed.  It doesn't work.

**Comment by raman777** [comment]
... way more not usable now with version 1.1.0 of the plugin (with 1.0.0, I ran into the same situation as described above) ...

- really nothing opens after pressing the plus button in  payara servers (no dialog, no input field)
- an error shows up when issuing the command "add payara server": 
  "Command Payara: Add payara server resulted in an error (command payara.server.add not found)"

![grafik](https://user-images.githubusercontent.com/61283890/123810487-ba0c8500-d8f2-11eb-9aff-e9c947bbf3b2.png)

My environment: Win10, VsCode 1.57.1, Java 11

**Comment by user790235692** [comment]
> ... way more not usable now with version 1.1.0 of the plugin (with 1.0.0, I ran into the same situation as described above) ...
> 
> * really nothing opens after pressing the plus button in  payara servers (no dialog, no input field)
> * an error shows up when issuing the command "add payara server":
>   "Command Payara: Add payara server resulted in an error (command payara.server.add not found)"
> 
> ![grafik](https://user-images.githubusercontent.com/61283890/123810487-ba0c8500-d8f2-11eb-9aff-e9c947bbf3b2.png)
> 
> My environment: Win10, VsCode 1.57.1, Java 11

Same issue here.

**Comment by f-gozie** [comment]
Currently having the exact same issue on Ubuntu 20.04

**Comment by f-gozie** [comment]
So, I've been having this same problem, but I came across a fix on one of these threads. Firstly, toggle your developers console using `Help > Toggle Developer Tools > Console`, then try adding the domain. In my case, I could see an error saying my Java path wasn't properly set, so I edited my .bashrc file to point to the right direction. Not sure if this solution applies to everyone but it's worth a shot.

**Comment by miguel-martin** [comment]
@f-gozie answer helped me to solve the issue. It was indeed due to JAVA_HOME not being correctly set.

In case you are using bash, put this in your .bash_profile
```
export JAVA_HOME=`/usr/libexec/java_home -v 8`
```

Then run:
`source .bash_profile`

Close and open VSC again.

**Comment by Chaitanya052002** [comment]
My all paths in environment variable of my windows was correct and still was facing same problem of "not able to click domain name" in vscode payara extension. 

However i changed the java.home and java.jdt.ls.java.home values in settings.json in settings section of vscode to my required java path example : "C:\\Program Files\\Java\\jdk-11".

PROBLEM SOLVED
