### ISSUE TITLE
Dependency not working

### ISSUE THREAD

**Issue by chaitra-daddolu** [payara/ecosystem-support#13]
I used this a dependency in pom.xml but I was not able to get the results. Actually I wanted to activate a profile based on git branch. So I want to use regex for matching master branch. But I'm not able to do that.

**Comment by MeroRai** [comment]
Please, direct all of your questions to the official Payara Community Google Forum (https://groups.google.com/forum/#!forum/payara-forum) to receive assistance. We’ll proceed to close this issue.
