### ISSUE TITLE
ClassNotFoundException: org.glassfish.jersey.client.JerseyClientBuilder

### ISSUE THREAD

**Issue by hantsy** [payara/ecosystem-support#15]
Not sure if the change is desired in the 2.4 snapshots, it seems all Jaxrs resources tests are broken when running the  Arquillian tests against the Payara Managed adapter.

https://github.com/hantsy/jakartaee8-starter-boilerplate/pull/116/

**Comment by hantsy** [comment]
The v2.4 release branch got the same issue. https://github.com/hantsy/jakartaee8-starter-boilerplate/pull/123/checks?check_run_id=2223418242

**Comment by hantsy** [comment]
@fturizo It seems  I have to add `payara-client-ee8` explicitly to make it work, the former 2.3 did not require it.

**Comment by fturizo** [comment]
We're sorry but this issue fell through the cracks in the past years, please re-test with the current version of the Arquillian adapters to make sure the issue is still present and if that is the case, raise a new issue with a more complete report.
