### ISSUE TITLE
Runtime Could not inject members when runing JMS tests on Payara Micro

### ISSUE THREAD

**Issue by hantsy** [payara/ecosystem-support#16]
I am trying to add a simple [jms branch](https://github.com/hantsy/jakartaee8-starter-boilerplate/tree/jms) to my sample project, the codes are stupid and simple, just a hello level producer and consumer.

The testing code is [HelloJmsTest](https://github.com/hantsy/jakartaee8-starter-boilerplate/blob/jms/src/test/java/com/example/it/HelloJmsTest.java).

The details of the build result is:

https://github.com/hantsy/jakartaee8-starter-boilerplate/pull/110/checks?check_run_id=1844060356

**Comment by hantsy** [comment]
JMS tests against Payara Micro still failed using 2.4.4. https://github.com/hantsy/jakartaee8-starter-boilerplate/runs/3619210090

**Comment by hantsy** [comment]
JMS tests against Payara Micro still failed using 2.4.5. https://github.com/hantsy/jakartaee8-starter-boilerplate/runs/3732414183?check_suite_focus=true

**Comment by fturizo** [comment]
Doesn't seem to be an ecosystem issue, please raise a new issue in the main Payara Community repository: https://github.com/payara/Payara/issues.
