### ISSUE TITLE
 NoSuchEJB The EJB does not exist when running tests against Micro 

### ISSUE THREAD

**Issue by hantsy** [payara/ecosystem-support#17]
I created a simple [EJB branch](https://github.com/hantsy/jakartaee8-starter-boilerplate/tree/ejb) to add a simple Stateful EJB, the test failed on Payara Micro.

With an exception ** NoSuchEJB The EJB does not exist**.

Check the details from Github Actions CI.

https://github.com/hantsy/jakartaee8-starter-boilerplate/pull/111/checks?check_run_id=1843865767

**Comment by hantsy** [comment]
EJB tests against Payara Micro still failed when using 2.4.4, https://github.com/hantsy/jakartaee8-starter-boilerplate/runs/3619210090

**Comment by hantsy** [comment]
Arquillian tests against Payara Micro still failed when using 2.4.5,https://github.com/hantsy/jakartaee8-starter-boilerplate/runs/3732414183?check_suite_focus=true

**Comment by fturizo** [comment]
We're sorry but this issue fell through the cracks in the past years, please re-test with the current version of the Arquillian adapters to make sure the issue is still present and if that is the case, raise a new issue with a more complete report.
