### ISSUE TITLE
javax.ejb.TransactionRolledbackLocalException when running against Micro and embedded

### ISSUE THREAD

**Issue by hantsy** [payara/ecosystem-support#18]
Currently, I am trying to add testing codes to the cargo tracker application.

https://github.com/hantsy/cargotracker/

The tests which are **passed with Payara managed container** failed with Micro and embedded container, there a lot of EJB transaction exception. 

```bash
javax.ejb.TransactionRolledbackLocalException: Exception thrown from bean: javax.ws.rs.ProcessingException: 
java.net.ConnectException: Connection refused (Connection refused)
```

The complete logging can be found there.

https://github.com/hantsy/cargotracker/runs/1789325545

Not sure what is missing in the micro and embedded config?

**Comment by fturizo** [comment]
We're sorry but this issue fell through the cracks in the past years, please re-test with the current version of the plugin to make sure the issue is still present and if that is the case, raise a new issue with a more complete report.
