### ISSUE TITLE
Exactly-once semantics with Kafka Connector

### ISSUE THREAD

**Issue by jfbenckhuijsen** [payara/ecosystem-support#19]
Hi,

I was looking at the Kafka JCA adapter to start using it in our backend system we're currently developing. One of the issues I ran into is a lack of support for exactly-once semantics in processing the Kafka messages. The current connector only supports at-least and at-most once delivery of messages. 

Of course, Kafka doesn't support exactly-once by itself, however you can do this yourself, by providing the necessary extension points. The current structure of the JCA adapter however doesn't allow access to these extension points. I started working on a PR to expose these extension points through the JCA adapter, but then ran into the issue the current implementation of the JCA adapter has some limitations with regards to how threads are managed that this will never work. Basically the current approach cannot guarantee ordering of message delivery, which is really a nice feature of Kafka we need.

I could extend the PR with a rewrite also of the threading handling to alleviate this, however I first want to verify with you guys if such a PR would be accepted as this would basically be quite an incompatible change. 

(Btw. I'm working on this from the company I work for, meaning I still have to get the OK to publish such a PR in the first place, so no guarantees there. For obvious reasons I cannot disclose the company atm).

**Comment by fturizo** [comment]
We're sorry but this issue fell through the cracks in the past years, please let us know in a more complete report if you still require this enhancement by raising a new issue.
