### ISSUE TITLE
[Kafka Clarification] Messages commitment manual control

### ISSUE THREAD

**Issue by imbananko** [payara/ecosystem-support#20]
Hello,
I'm using manually built `KafkaRAR`
And my question: Is there a way to control offset commitment of incoming messages?
For example I have:
```
@OnRecord(topics = {"test-topic"})
    public void getMessage(ConsumerRecords record) {
        //business
    }
```
If some exception happens, how can I tell producer to keep the current offset?
Or to resend same message (with the same offset)?

**Comment by AlanRoth** [comment]
Hi @imbananko, 

Questions like this are best posted in our [Payara Forum](https://groups.google.com/g/payara-forum).

Thank you for your understanding,
Alan
