### ISSUE TITLE
Update Payara Platform Tools for IntelliJ IDEA 2021.1 - FISH-1292

### ISSUE THREAD

**Issue by Nawrok** [payara/ecosystem-support#24]
I would like to request an update to the Payara Platform Tools plugin for IntelliJ IDEA 2021.1.

## Ecosystem Tool
Payara Platform Tools - Intellij Plugin

**Comment by MeroRai** [comment]
Hi @Nawrok, there is already a plan to make the Payara Platform compatible with IntelliJ IDEA 2021.1.

**Comment by Pilpin** [comment]
Hello, would it be possible to have an ETA ? 
Thank you !

**Comment by MeroRai** [comment]
Hi @Pilpin, sorry at this moment we can't provide you with an ETA.  But there is a plan in place to fix the issue. Thank you for your understanding.

**Comment by MeroRai** [comment]
Hi @Pilpin and @Nawrok, this issue has been fixed by https://github.com/payara/ecosystem-intellij-community-plugin/pull/9.
