### ISSUE TITLE
Payara Managed testing failed upgrade to 5.2021.2

### ISSUE THREAD

**Issue by hantsy** [payara/ecosystem-support#25]
This PR caused Payara Manged testing codes failed. 

https://github.com/hantsy/cargotracker/pull/43

See the details: 

https://github.com/hantsy/cargotracker/pull/43/checks?check_run_id=2337517128#step:6:4091

**Comment by hantsy** [comment]
Same error here when upgraded to 5.2021.2.
https://github.com/hantsy/jakartaee8-starter-boilerplate/runs/2339028383#step:5:7351

**Comment by OndroMih** [comment]
Hi, the reason for failed tests is that Payara Server can't start because:

> There is a process already using the admin port 4848 -- it could be another instance of Payara Server or Payara Micro

Later, when the tests want to shut down Payara Server, it's not running:

> CLI306: Warning - The server located at /home/runner/work/cargotracker/cargotracker/target/payara5/glassfish/domains/domain1 is not running. 

Please make sure that no Payara Server is running before you start the tests and that the port 4848 isn't occupied on your machine. Then run the tests.

**Comment by hantsy** [comment]
Check the latest error link on Github actions.

https://github.com/hantsy/cargotracker/runs/2341810423

It worked in before versions.

Check my workflow file.

https://github.com/hantsy/cargotracker/blob/master/.github/workflows/it-with-arq-payara-managed.yml

Not sure if it is the problem of  setup-java v2, after upgraded to setup-java@v2 and the latest Payara, several Payara workflow failed in my Github projects.

**Comment by hantsy** [comment]
Not sure if there are some changes in the Github actions infra, all arquilllian tests against Payara/Glassfish adapters failed now.

https://github.community/t/arquillian-test-against-payara-glasfish-failed-due-to-4848-port-in-use/174879

**Comment by hantsy** [comment]
In https://github.com/hantsy/cargotracker/ , I removed other Payara-related workflow, only left Payara managed adapter to run the testing codes, still failed.

I am afraid there are some changes from Github actions to affect this.

In the  https://github.com/hantsy/jakartaee9-starter-boilerplate, the Glassfish managed and remote adapter also failed now, either setup-java v1 or v2.

**Comment by hantsy** [comment]
Till now, almost all Payara/GlassFish related workflows which worked well in the past months or years are failed in all of my repositories.

*  https://github.com/hantsy/jakartaee8-starter-boilerplate
*  https://github.com/hantsy/jakartaee9-starter-boilerplate
*  https://github.com/hantsy/cargotracker/

**Comment by hantsy** [comment]
@OndroMih I can confirm it could be 100% a problem related to Github actions environment. https://github.com/actions/setup-java/issues/158#issuecomment-821931108, but can not find why it happened. I created a new Circle CI config using the same scripts, it is always successful. Not sure if there are some specific behaviors in the Payara/GlassFish adapters. And if there is some approaches to fix this.

**Comment by hantsy** [comment]
@OndroMih The `4848 error` is disappeared in this two days.
