### ISSUE TITLE
Enhancement:  Add  Payara 6  Support to Arquillian Adapter

### ISSUE THREAD

**Issue by hantsy** [payara/ecosystem-support#28]
Currently Payara Arquillian adapters lack support of Jakarta EE 9 and Payara 6 support.

**Comment by jGauravGupta** [comment]
Created internal ticket FISH-5641 to address the task.

**Comment by hantsy** [comment]
When is it will be published to the public repository for tasting?

**Comment by jGauravGupta** [comment]
It will be published to Maven Central soon. You may already try the 3.0.Alpha1 from the [payara-artifacts repository ](https://nexus.payara.fish/#browse/browse:payara-artifacts:fish%2Fpayara%2Farquillian%2Fpayara-client-ee9%2F3.0.alpha1)

**Comment by hantsy** [comment]
Thanks @jGauravGupta. I updated my sample, add Payara 6 and Payara Arquillian Adapter 3.0.alpha1, see:
https://github.com/hantsy/jakartaee9-starter-boilerplate/pull/64

**Comment by jGauravGupta** [comment]
Released Payara Arquillian Connector v3.0-alpha2 under ticket FISH-5885
https://repo1.maven.org/maven2/fish/payara/arquillian/payara-client-ee9/3.0.alpha2/
