### ISSUE TITLE
Bug Report:  Cannot setup payara server, part 2

### ISSUE THREAD

**Issue by raman777** [payara/ecosystem-support#29]
quote from #1 "Always stuck at step 4: select an exist domain. I can't select domain1 and can't go through, also tried with add new domain, also not working."

Please consider reopening #1, because this issue is still not solved, moreover it is now way more unusable with version 1.1.0 of the plugin (with 1.0.0, I ran into the same situation as described above in the quote):

- really nothing opens after pressing the plus button in payara servers (no dialog, no input field)
- an error shows up when issuing the command "add payara server" via ctrl-shift-p:
    "Command Payara: Add payara server resulted in an error (command payara.server.add not found)"

![grafik](https://user-images.githubusercontent.com/61283890/123812307-45d2e100-d8f4-11eb-88a4-8a782ceaa1e6.png)

My environment: Win10, VsCode 1.57.1, Java 11

**Comment by Khinsu** [comment]
I am facing the same Issue.
Microsoft VS Code_1.57.1
Payara Tools for Visual Studio Code v.1.10

All servers are gone and cant add new ones.

With the old Version Payara Tools for Visual Studio Code 1.0.0 everything is working fine.
![image](https://user-images.githubusercontent.com/1149343/123951993-aec66180-d9a5-11eb-9a3d-0dc2c6315e1a.png)

**Comment by raman777** [comment]
Meanwhile, I forked the project and did some research:

1. extension 1.1.0 probably is bundled incorrectly --> building the extension locally shows the same effect - until you do a "npm install" in the extensions folder first. --> Thus, the plugin does simply not start in version 1.1.0
2. after performing that, the plugin behaves exactly as version 1.0.0 when adding a local server: you get until the "select a domain" step - and no selection is possible (as described in #1 ) --> Thus, it is not possible to add a local server.
3. I also tried to add a remote server first (to check, whether te problem is due to adding a first server only) a remote server (this was possible) - but also without luck for adding a local server in a second step
**So, can someone else please check in a environment where payara servers are already added by a former version of the plugin, if it would be possible with v 1.0.0 or 1.1.0 would be possible to add a second or third one?**

So neither v 1.1.0 nor 1.0.0 seem to work.

BTW: I checked it in several evironments (Win10, Ubuntu 18.04, Linux Mint 19, ...) with the same VScode version (1.57.1)

**Comment by jGauravGupta** [comment]
Hi,

I released Payara tools v1.1.1 which fixes the packaging issue (should be available soon in the marketplace).


> Always stuck at step 4: select an exist domain. I can't select domain1 and can't go through, also tried with add new domain, also not working.

Please share the console log from `Help > Toogle Developer Tools > Console tab` as it is not reproducible for me. 
/cc @MeroRai

**Comment by danransom** [comment]
Here's my console log. I've tried changing my JAVA_HOME environmental variable to several different JDK and JRE installs:

`console.ts:137 [Extension Host] rejected promise not handled within 1 second: Error: Java Process C:\Program Files\Java\jdk-17\bin\bin\jps.exe executable for payara5 was not found
v @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:35
_doInvokeHandler @ rpcProtocol.ts:472
_invokeHandler @ rpcProtocol.ts:457
_receiveRequest @ rpcProtocol.ts:373
_receiveOneMessage @ rpcProtocol.ts:295
(anonymous) @ rpcProtocol.ts:160
fire @ event.ts:577
fire @ ipc.net.ts:513
_receiveMessage @ ipc.net.ts:871
(anonymous) @ ipc.net.ts:710
fire @ event.ts:577
acceptChunk @ ipc.net.ts:286
(anonymous) @ ipc.net.ts:247
k @ ipc.net.ts:50
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188
console.ts:137 [Extension Host] stack trace: Error: Java Process C:\Program Files\Java\jdk-17\bin\bin\jps.exe executable for payara5 was not found	at PayaraLocalServerInstance.checkAliveStatusUsingJPS (c:\Users\djransom\.vscode\extensions\payara.payara-vscode-1.1.1\out\main\fish\payara\server\PayaraLocalServerInstance.js:111:19)	at registerServer (c:\Users\djransom\.vscode\extensions\payara.payara-vscode-1.1.1\out\main\fish\payara\server\PayaraServerInstanceController.js:97:42)	at c:\Users\djransom\.vscode\extensions\payara.payara-vscode-1.1.1\out\main\fish\payara\server\PayaraServerInstanceController.js:125:25	at PayaraServerInstanceController.<anonymous> (c:\Users\djransom\.vscode\extensions\payara.payara-vscode-1.1.1\out\main\fish\payara\server\PayaraServerInstanceController.js:346:13)	at Generator.next (<anonymous>)	at fulfilled (c:\Users\djransom\.vscode\extensions\payara.payara-vscode-1.1.1\out\main\fish\payara\server\PayaraServerInstanceController.js:5:58)	at processTicksAndRejections (internal/process/task_queues.js:93:5)
v @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:35
_doInvokeHandler @ rpcProtocol.ts:472
_invokeHandler @ rpcProtocol.ts:457
_receiveRequest @ rpcProtocol.ts:373
_receiveOneMessage @ rpcProtocol.ts:295
(anonymous) @ rpcProtocol.ts:160
fire @ event.ts:577
fire @ ipc.net.ts:513
_receiveMessage @ ipc.net.ts:871
(anonymous) @ ipc.net.ts:710
fire @ event.ts:577
acceptChunk @ ipc.net.ts:286
(anonymous) @ ipc.net.ts:247
k @ ipc.net.ts:50
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188
mainThreadExtensionService.ts:63 [[object Object]]Java Process C:\Program Files\Java\jdk-17\bin\bin\jps.exe executable for payara5 was not found
$onExtensionRuntimeError @ mainThreadExtensionService.ts:63
_doInvokeHandler @ rpcProtocol.ts:472
_invokeHandler @ rpcProtocol.ts:457
_receiveRequest @ rpcProtocol.ts:373
_receiveOneMessage @ rpcProtocol.ts:295
(anonymous) @ rpcProtocol.ts:160
fire @ event.ts:577
fire @ ipc.net.ts:513
_receiveMessage @ ipc.net.ts:871
(anonymous) @ ipc.net.ts:710
fire @ event.ts:577
acceptChunk @ ipc.net.ts:286
(anonymous) @ ipc.net.ts:247
k @ ipc.net.ts:50
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188
mainThreadExtensionService.ts:64 Error: Java Process C:\Program Files\Java\jdk-17\bin\bin\jps.exe executable for payara5 was not found
	at PayaraLocalServerInstance.checkAliveStatusUsingJPS (c:\Users\djransom\.vscode\extensions\payara.payara-vscode-1.1.1\out\main\fish\payara\server\PayaraLocalServerInstance.js:111:19)
	at registerServer (c:\Users\djransom\.vscode\extensions\payara.payara-vscode-1.1.1\out\main\fish\payara\server\PayaraServerInstanceController.js:97:42)
	at c:\Users\djransom\.vscode\extensions\payara.payara-vscode-1.1.1\out\main\fish\payara\server\PayaraServerInstanceController.js:125:25
	at PayaraServerInstanceController.<anonymous> (c:\Users\djransom\.vscode\extensions\payara.payara-vscode-1.1.1\out\main\fish\payara\server\PayaraServerInstanceController.js:346:13)
	at Generator.next (<anonymous>)
	at fulfilled (c:\Users\djransom\.vscode\extensions\payara.payara-vscode-1.1.1\out\main\fish\payara\server\PayaraServerInstanceController.js:5:58)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:64
_doInvokeHandler @ rpcProtocol.ts:472
_invokeHandler @ rpcProtocol.ts:457
_receiveRequest @ rpcProtocol.ts:373
_receiveOneMessage @ rpcProtocol.ts:295
(anonymous) @ rpcProtocol.ts:160
fire @ event.ts:577
fire @ ipc.net.ts:513
_receiveMessage @ ipc.net.ts:871
(anonymous) @ ipc.net.ts:710
fire @ event.ts:577
acceptChunk @ ipc.net.ts:286
(anonymous) @ ipc.net.ts:247
k @ ipc.net.ts:50
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188
console.ts:137 [Extension Host] rejected promise not handled within 1 second: Error: Java Process C:\Program Files\Java\jdk-17\bin\bin\jps.exe executable for payara5 was not found
v @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:35
_doInvokeHandler @ rpcProtocol.ts:472
_invokeHandler @ rpcProtocol.ts:457
_receiveRequest @ rpcProtocol.ts:373
_receiveOneMessage @ rpcProtocol.ts:295
(anonymous) @ rpcProtocol.ts:160
fire @ event.ts:577
fire @ ipc.net.ts:513
_receiveMessage @ ipc.net.ts:871
(anonymous) @ ipc.net.ts:710
fire @ event.ts:577
acceptChunk @ ipc.net.ts:286
(anonymous) @ ipc.net.ts:247
k @ ipc.net.ts:50
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188
console.ts:137 [Extension Host] stack trace: Error: Java Process C:\Program Files\Java\jdk-17\bin\bin\jps.exe executable for payara5 was not found	at PayaraLocalServerInstance.checkAliveStatusUsingJPS (c:\Users\djransom\.vscode\extensions\payara.payara-vscode-1.1.1\out\main\fish\payara\server\PayaraLocalServerInstance.js:111:19)	at registerServer (c:\Users\djransom\.vscode\extensions\payara.payara-vscode-1.1.1\out\main\fish\payara\server\PayaraServerInstanceController.js:97:42)	at c:\Users\djransom\.vscode\extensions\payara.payara-vscode-1.1.1\out\main\fish\payara\server\PayaraServerInstanceController.js:125:25	at PayaraServerInstanceController.<anonymous> (c:\Users\djransom\.vscode\extensions\payara.payara-vscode-1.1.1\out\main\fish\payara\server\PayaraServerInstanceController.js:346:13)	at Generator.next (<anonymous>)	at fulfilled (c:\Users\djransom\.vscode\extensions\payara.payara-vscode-1.1.1\out\main\fish\payara\server\PayaraServerInstanceController.js:5:58)	at processTicksAndRejections (internal/process/task_queues.js:93:5)
v @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:35
_doInvokeHandler @ rpcProtocol.ts:472
_invokeHandler @ rpcProtocol.ts:457
_receiveRequest @ rpcProtocol.ts:373
_receiveOneMessage @ rpcProtocol.ts:295
(anonymous) @ rpcProtocol.ts:160
fire @ event.ts:577
fire @ ipc.net.ts:513
_receiveMessage @ ipc.net.ts:871
(anonymous) @ ipc.net.ts:710
fire @ event.ts:577
acceptChunk @ ipc.net.ts:286
(anonymous) @ ipc.net.ts:247
k @ ipc.net.ts:50
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188
mainThreadExtensionService.ts:63 [[object Object]]Java Process C:\Program Files\Java\jdk-17\bin\bin\jps.exe executable for payara5 was not found
$onExtensionRuntimeError @ mainThreadExtensionService.ts:63
_doInvokeHandler @ rpcProtocol.ts:472
_invokeHandler @ rpcProtocol.ts:457
_receiveRequest @ rpcProtocol.ts:373
_receiveOneMessage @ rpcProtocol.ts:295
(anonymous) @ rpcProtocol.ts:160
fire @ event.ts:577
fire @ ipc.net.ts:513
_receiveMessage @ ipc.net.ts:871
(anonymous) @ ipc.net.ts:710
fire @ event.ts:577
acceptChunk @ ipc.net.ts:286
(anonymous) @ ipc.net.ts:247
k @ ipc.net.ts:50
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188
mainThreadExtensionService.ts:64 Error: Java Process C:\Program Files\Java\jdk-17\bin\bin\jps.exe executable for payara5 was not found
	at PayaraLocalServerInstance.checkAliveStatusUsingJPS (c:\Users\djransom\.vscode\extensions\payara.payara-vscode-1.1.1\out\main\fish\payara\server\PayaraLocalServerInstance.js:111:19)
	at registerServer (c:\Users\djransom\.vscode\extensions\payara.payara-vscode-1.1.1\out\main\fish\payara\server\PayaraServerInstanceController.js:97:42)
	at c:\Users\djransom\.vscode\extensions\payara.payara-vscode-1.1.1\out\main\fish\payara\server\PayaraServerInstanceController.js:125:25
	at PayaraServerInstanceController.<anonymous> (c:\Users\djransom\.vscode\extensions\payara.payara-vscode-1.1.1\out\main\fish\payara\server\PayaraServerInstanceController.js:346:13)
	at Generator.next (<anonymous>)
	at fulfilled (c:\Users\djransom\.vscode\extensions\payara.payara-vscode-1.1.1\out\main\fish\payara\server\PayaraServerInstanceController.js:5:58)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:64
_doInvokeHandler @ rpcProtocol.ts:472
_invokeHandler @ rpcProtocol.ts:457
_receiveRequest @ rpcProtocol.ts:373
_receiveOneMessage @ rpcProtocol.ts:295
(anonymous) @ rpcProtocol.ts:160
fire @ event.ts:577
fire @ ipc.net.ts:513
_receiveMessage @ ipc.net.ts:871
(anonymous) @ ipc.net.ts:710
fire @ event.ts:577
acceptChunk @ ipc.net.ts:286
(anonymous) @ ipc.net.ts:247
k @ ipc.net.ts:50
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188
`

**Comment by Giovy27072** [comment]
Same problem on Endeavor OS (Arch linux) using VS Code 1.75.1-1 and Papayara plugin 1.2.2

**Comment by ojuschugh1** [comment]
Hi, I just used VS code IDE and Payara tools extension for Payara 6 and Payara 5  server both but I did not face any issues.
I guess it is now been resolved .

**Comment by fturizo** [comment]
Closing the issue due to inactivity.
