### ISSUE TITLE
Enhancement: Release new version of payara/Cloud-Connectors

### ISSUE THREAD

**Issue by bh-tt** [payara/ecosystem-support#34]
# Description #
----------

The [0.7.0](https://github.com/payara/Cloud-Connectors/milestone/3?closed=1) milestone has been closed with 0 remaining issues (since may 24). Is there an ETA on when it will be released?

## Expected Outcome

New version 0.7.0 is released

## Current Outcome

Our company is currently maintaining our own fork of the project in order to use it (we need https://github.com/payara/Cloud-Connectors/pull/193). Last release was over a year ago.

## Ecosystem Tool

https://github.com/payara/Cloud-Connectors

**Comment by lpiet** [comment]
we are looking for this too

**Comment by smillidge** [comment]
OK will get on it.

**Comment by OndroMih** [comment]
0.7.0 has been released already: https://github.com/payara/Cloud-Connectors/releases/tag/0.7.0. Closing this issue.
