### ISSUE TITLE
Enhancement: Add gradle.home documentation to vscode-plugin

### ISSUE THREAD

**Issue by bh-tt** [payara/ecosystem-support#38]
# Description #
----------
When using a local gradle installation the `Run on Payara Server` option fails with a `Gradle home not found` error if the GRADLE_HOME variable is not defined. This can be fixed by adding the `gradle.home` setting to your local gradle installation. However, this is not documented anywhere. 

## Expected Outcome
A plugin should list used properties in its README. This section is not present at this time.

## Current Outcome
In order to find a fix I had to search through the source code of the plugin, finding that it does a lookup of `gradle.home` [here](https://github.com/payara/ecosystem-vscode-plugin/blob/12169addf411110de7d1646330552615eed4b992/src/main/fish/payara/project/Gradle.ts#L171).

## Ecosystem Tool
VS Code

**Comment by JamesHillyard** [comment]
Hi @bh-tt,

Thank you for bringing this issue to our attention, after looking through our documentation and README files, I agree this is not clear, not only for our VS Code plugin, but over all our ecosystem tools. I have raised an internal issue to discuss, review and hopefully improve this issue.

I will update you once a decision on how to proceed with this has been reached, however this property will be documented in our technical documentation at the very least.

Thanks,
James

**Comment by JamesHillyard** [comment]
Hi @bh-tt,

We decided to revamp the Ecosystem IDE documentation, where this is more clearly documented. This documentation will be published soon and we hope will clarify this for users in the future.

Thanks,
James
