### ISSUE TITLE
Payara Tools - Add suport for Intellij 2021.3 /FISH-5884

### ISSUE THREAD

**Issue by rmitoi** [payara/ecosystem-support#39]
# Description #
----------

Payara Tools is not supported in the latest version of IntelliJ

## Expected Outcome ##

After upgrading the Payara Tools is marked as not supported and cannot be used in the IDE.

## Current Outcome ##

The plugin is disabled and a message that it requires build 213 or earlier is displayed in the Plugins section of IntelliJ

## Environment ##

- **Ecosystem Plugin/Tool**: Intellij 
- **Operating System**: Windows

**Comment by rdebusscher** [comment]
Hi,

Thank you for the report. We have already an internal ticket to update to the latest IntelliJ plugin API as we got notified earlier this week of an incompatible change.

Rudy

**Comment by jGauravGupta** [comment]
Payara Intellij IDEA tools v1.4.0 have been released with the Intellij 2021.3 compatibility fix.
Payara Platform Tools 1.4.0: https://plugins.jetbrains.com/plugin/15114-payara-platform-tools/versions/stable/153758
Payara Micro-Community Tools 1.4.0: https://plugins.jetbrains.com/plugin/15445-payara-micro-community-tools/versions/stable/153755
