### ISSUE TITLE
FISH-1448 Artifacts to deploy can not be reordered

### ISSUE THREAD

**Issue by bleicher** [payara/ecosystem-support#4]
but are ordered alphabetically, always.
Other than in the glassfish plugin for IntelliJ, there are only Add/Remove/Edit buttons below the list of things to deploy,
no arrows to reorder this list. And my .war s and .ear s deploy in a certain order only.
Hope it is an easy copypaste-fix ...

Best, Markus

**Comment by JamesHillyard** [comment]
Hi @bleicher,

This enhancement has been implemented in the Payara Server Tools plugin 1.5 release, please update the plugin to the latest version to use this enhancement.

Best Regards,
James
