### ISSUE TITLE
Bug Report:  Could not find artifact fish.payara.arquillian:arquillian-payara-micro-managed:jar:3.0.alpha4

### ISSUE THREAD

**Issue by hantsy** [payara/ecosystem-support#42]
Renovate raised a new Pr to update my project to use Payara Arquillian 3.0.alpha4, but there is a failure due to lack of `fish.payara.arquillian:arquillian-payara-micro-managed:jar:3.0.alpha4`.

Check the details of the PR: https://github.com/hantsy/jakartaee9-starter-boilerplate/pull/217

**Comment by JamesHillyard** [comment]
Hi @hantsy,

Thank you for raising attention to the problem, I have informed the development team and they will work on resolving the issue.

Thank you,
James

**Comment by hantsy** [comment]
Is it fixed?
