### ISSUE TITLE
Bug Report:  Cannot add Payara Server to Eclipse IDE

### ISSUE THREAD

**Issue by hendrelouw73** [payara/ecosystem-support#43]
# Description #
----------

During the creation of a new server on Eclipse, the add and remove software dialogue is displayed with no applications listed and no path forward to complete the installation. This is a fresh install of Payara.

## Expected Outcome ##

Installed Payara server on Eclipse. 

## Current Outcome ##

Cannot install the Payara server on Eclipse.

## Steps to reproduce ## 

A new server is added under the Servers tab. Payara is selected as the server type. The Payara location and Java location are entered. Then the empty Add and Remove dialogue (the same dialogue that is used to add and remove projects from a server) is displayed with no applications to choose from and the next and finish buttons disabled. 

![Screenshot from 2022-04-08 11-24-18](https://user-images.githubusercontent.com/1856547/162407539-d22cbdad-9a33-400b-8581-2e013ab89bd2.png)

## Environment ##

Payara 5
Open JDK 17
Ubuntu

**Comment by fturizo** [comment]
Moving over this issue to the ecosystem support project since this seems to be related to the Eclipse Dev Tools package.

**Comment by JamesHillyard** [comment]
Hi @hendrelouw73,

I am unable to reproduce this issue using [Eclipse IDE for Enterprise Java and Web Developers](https://www.eclipse.org/downloads/packages/release/2022-03/r/eclipse-ide-enterprise-java-and-web-developers) 2022-03 and the latest version of Payara Tools for Eclipse. Could you please give more details on how to reproduce this issue?

Thanks,
James

**Comment by hendrelouw73** [comment]
Thank you @JamesHillyard. Upgrading to the latest versions resolved my issue.
