### ISSUE TITLE
DeploymentException: No applications were found deployed to Payara Micro.

### ISSUE THREAD

**Issue by hantsy** [payara/ecosystem-support#46]
org.jboss.arquillian.container.spi.client.container.DeploymentException: No applications were found deployed to Payara Micro.

See the exception details:  https://github.com/hantsy/jakartaee8-starter-boilerplate/runs/6445144467?check_suite_focus=true

**Comment by JamesHillyard** [comment]
Hi @hantsy,

Please, can you provide a simple to follow scenario how to reproduce this on the latest release of Payara Community Edition? A reproducer should ideally follow the SSCCE rules: http://www.sscce.org/. It will greatly help us to find the cause and fix it.

Thanks,
James

**Comment by JamesHillyard** [comment]
Hi @hantsy,

Could you please provide an update on this issue, have you been able to resolve it or create a reproducer for me to investigate?

Thanks,
James

**Comment by hantsy** [comment]
My simple example project is easy to reproduce it.
https://github.com/hantsy/jakartaee8-starter-boilerplate

Check the Github actions log to view the complete log.

**Comment by fturizo** [comment]
We're sorry but this issue fell through the cracks in the past years, please re-test with the current version of the plugin to make sure the issue is still present and if that is the case, raise a new issue with a more complete report.
