### ISSUE TITLE
VM options not added / FISH-780

### ISSUE THREAD

**Issue by petrslavicek** [payara/ecosystem-support#5]
When I set custom VM option to Payara run configuration the option is not added to Payara startup VM parameters.
e.g.
-Dmy.custom.param=value
This value is not set and not writed to payara log on startup.

Payara Tool 1.1.0 and Intelij 2020.2.3 Ultimate

**Comment by JamesHillyard** [comment]
Hi @petrslavicek,

This issue has been resolved in the Payara Server Tools 1.5 release, please update the plugin to receive this fix.

Best Regards,
James
