### ISSUE TITLE
Bug Report: Eclipse Plugin Deploying Test Classes?

### ISSUE THREAD

**Issue by m-reza-rahman** [payara/ecosystem-support#55]
# Description #
----------
I think a bug was introduced in the Eclipse plugin or something is broken in the latest Eclipse and Payara. When I try to run a Maven application, the test classes are deployed as well, which should not happen. You can validate this using Cargo Tracker: https://github.com/eclipse-ee4j/cargotracker (just follow the steps here: https://github.com/eclipse-ee4j/cargotracker/wiki/Eclipse-IDE). This did not use to be the case. The deployment works fine while not using the plugin.

## Environment ##
Windows 11
JDK 17
Eclipse 2022-06

**Comment by JamesHillyard** [comment]
Hi @m-reza-rahman,

Could you please clarify further what you are experiencing, I was able to successfully deploy the cargo tracker app from Eclipse 2022-06 and I was unable to see test classes deployed from the Admin Console.

Thanks,
James

**Comment by m-reza-rahman** [comment]
I re-installed everything and it works now. I can no longer reproduce this. If it crops up again, I will re-open this issue.
