### ISSUE TITLE
Enhancement: Add compatibility for `Payara Platform Tools` plugin with Intellij `2022.3`.  / FISH-6860 

### ISSUE THREAD

**Issue by cristi-badila** [payara/ecosystem-support#59]
### Brief Summary

Add compatibility for `Payara Platform Tools` plugin with Intellij 2022.3.  

The currently released version, `1.4.0`. is no longer compatible with the latest release of IntelliJ. 

### Expected Outcome

Existing build configurations/features would work as expected after updating to the latest version of IntelliJ.

### Current Outcome

Updating the editor to the latest version results in broken/disabled build configurations and features.

### Ecosystem Tool

IntelliJ IDEA IDE Plugin

**Comment by StevenHachel** [comment]
Can we still expect an update this year? How did the incompatibility even come about?

Steven

**Comment by JamesHillyard** [comment]
Hi @cristi-badila and @StevenHachel,

This is a known issue with the latest version of IntelliJ. There were a large number of UI changes within the latest release, which is possibly the cause of the latest incompatibility. An internal issue `FISH-6860` has been raised to investigate and resolve the incompatibility so Payara Platform Tools can be used with IntelliJ 2022.3.

Best Regards,
James

**Comment by cristi-badila** [comment]
From what I can see the plugin was updated and works now as expected. Thanks!
