### ISSUE TITLE
Bug Report: Eclipse Payara Tools turns POM completion unusable

### ISSUE THREAD

**Issue by CarlosMOGoncalves** [payara/ecosystem-support#64]
### Brief Summary

Hello there,

I have just fresh installed Eclipse 2022-12 (the current latest) and fresh installed Payara Tools 2.0.0Beta1.

Immediately after installing Payara Tools, most things in POM editor (M2E, I think) has started behaving unexpectedly, breaking autocomplete and all around just throwing exceptions to the Error Log.

It's most common complaints are:
1 . `java.lang.IllegalArgumentException: URI is not absolute`
2. `A URL object was not found for the given URI dtds/sun-application_1_3-0.dtd from  fish.payara.eclipse.tools.server`

This effectively nulls the XML tools for Maven integration.

I am not sure the root cause is in Payara Tools because ever since they replaced the POM editor for this new one all kinds of problems with it have popped out. But this particular one is catastrophic (as in everything from it stops working) and started to happen only AFTER the plugin was installed and seems related to it by the exceptions.

### Expected Outcome

I expect the POM completion tool to be working nromally, loading suggestions for auto-completion. Just doing its normal thing

### Current Outcome

Well, as soon as the Payara plugin is installed, the POM editor, among other things will stop working and throwing exceptions.
Here are some of the examples:

1. When hovering over any part of the POM. Here I am hovering over this dependency. It writes those logs on the Erro Log:
![image](https://user-images.githubusercontent.com/2636004/212066061-349c5c1c-3818-4737-8342-a10caea79f15.png)

2. On the same screen (POM editor) right click and navigate to Code Actions:
![image](https://user-images.githubusercontent.com/2636004/212066377-7b97b80e-54ac-4dd3-a4e1-f239515ddd09.png)

3. On the Preferences Menu select XML(Wild Web Developer) and then Catalog and this happens:
![image](https://user-images.githubusercontent.com/2636004/212066991-f8b6744b-9326-4ff6-9695-4ec8b36c7fff.png)

In sum, it pretty much renders POM editor unusable, because it also stops every other auto-completion to be suggested.
In this part I think it blocks the POM editor from loading other schemas as soon as it gets that `IllegalArgumentException` from not finding the Payara one.

### Reproducer

Well, I think any application will do to test this out, but in any case here's a reproducer.
This is simple REST app written for Payara Micro, you can check it out [here](https://github.com/CarlosMOGoncalves/eclipse-issue-tester.git).

1. Install Eclipse IDE for Enterprise Java and Web Developers 2022-12
2. Install Payara Tools 2.0.0Beta1 (https://raw.githubusercontent.com/payara/ecosystem-eclipse-plugin/release-artifacts/repository/latest)
3. Checkout that application
4. Open its POM and just perform some of the steps I have pointed above

### Operating System

Windows 10 Enterprise

### JDK Version

Amazon Corretto-11.0.16.9.1

### Ecosystem Tool

Eclipse IDE Plugin

**Comment by mickaelistria** [comment]
`A URL object was not found for the given URI dtds/sun-application_1_3-0.dtd from  fish.payara.eclipse.tools.server` is the main issue here, it looks like this fish.payara.eclipse.tools.server is faulty of providing path to incorrect files in its plugin.xml

**Comment by shub8968** [comment]
#62 Related to it.

**Comment by CarlosMOGoncalves** [comment]
Hello. I just wanted to say that this issue has been fixed.
You can close it.
Cheers

**Comment by shub8968** [comment]
Closing as fixed.
