### ISSUE TITLE
Bug Report: Payara tools [not found] in eclipse marketplace or repository. / FISH-7012

### ISSUE THREAD

**Issue by LucasBarberisPerez** [payara/ecosystem-support#65]
### Brief Summary

Since 24 january i've been trying to install payara tools from the marketplace and also from their repository with no success.

repository link with 404 : https://raw.githubusercontent.com/payara/ecosystem-eclipse-plugin/release-artifacts/repository/latest

### Expected Outcome

Get plugin payara tools installed

### Current Outcome

![error1](https://user-images.githubusercontent.com/65420217/215294712-882e9aed-9090-4fd3-8cc9-1f67d21d3640.PNG)
![error2](https://user-images.githubusercontent.com/65420217/215294713-285a1c5a-869a-4a74-8403-64a1dd03ab11.PNG)

### Reproducer

Produced in a fresh eclipse 2021 install

1- eclipse marketplace and try to install payara tools.

2-eclipse -> install new software -> insert the repository link.

### Operating System

windows 10

### JDK Version

jdk1.8.0_202

### Ecosystem Tool

Eclipse IDE Plugin

**Comment by Elifzeynepedman** [comment]
Hi @Luksdanvip-OG,

This has been escalated as `FISH-7012` to our Platform development team.

Best Regards,
Elif

**Comment by Elifzeynepedman** [comment]
Hi @Luksdanvip-OG,

As this issue has been fixed, I will continue to close this issue.

Thank You,
Elif
