### ISSUE TITLE
Bug Report: Eclipse Payara Tools Not able to launch server

### ISSUE THREAD

**Issue by zuryx** [payara/ecosystem-support#67]
### Brief Summary

Eclipse Version: 2021-12 (4.22.0)
Eclipse Build id: 20211202-1639
Payara version: 5.193

Hi everybody :) ,

When I try to launch payara...

<img width="1513" alt="image" src="https://user-images.githubusercontent.com/20054168/236074627-443040c5-6ce6-4d86-8b18-4f5807a830a4.png">

I got the following error:

<img width="1234" alt="image" src="https://user-images.githubusercontent.com/20054168/236074754-7c3def02-d918-4f27-b4d8-4e754b8285a9.png">

### Expected Outcome

Payara should start in the same way I'm available to do it from terminal with the following command:

` ./bin/asadmin start-domain domain1`

<img width="713" alt="image" src="https://user-images.githubusercontent.com/20054168/236075838-31947d3c-780a-4d88-807e-de6f4bb348ee.png">

### Current Outcome

Payara fails with the following error:

<img width="1234" alt="image" src="https://user-images.githubusercontent.com/20054168/236075012-4304c662-6904-4d7d-bb32-e1a819c2d7ac.png">

`Unrecognized option: --add-opens=java.base/jdk.internal.loader=ALL-UNNAMED
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.`

Eclipse .log

!ENTRY fish.payara.eclipse.tools.server 4 150 2023-05-03 18:34:10.700
!MESSAGE Unable to start server due following issues:
!STACK 0
fish.payara.eclipse.tools.server.exceptions.PayaraLaunchException: Launch process failed with exit code 1
	at fish.payara.eclipse.tools.server.starting.PayaraStartJob.call(PayaraStartJob.java:116)
	at fish.payara.eclipse.tools.server.starting.PayaraStartJob.call(PayaraStartJob.java:1)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

### Reproducer

1. Create new payara server and runtime environment
<img width="1214" alt="image" src="https://user-images.githubusercontent.com/20054168/236075473-6dacb74d-b033-4bbd-a75a-e45bcfff2640.png">
2. Start server
<img width="414" alt="image" src="https://user-images.githubusercontent.com/20054168/236075512-b4c4f22a-530f-45dc-b1c9-73d596fdaf5d.png">
3. Start fails
<img width="922" alt="image" src="https://user-images.githubusercontent.com/20054168/236075552-11f6c0f8-376c-4a97-a148-533e17213ecb.png">

### Operating System

macOS Monterey

### JDK Version

JDK 1.8.0_162

### Ecosystem Tool

Eclipse IDE Plugin

**Comment by deetewari** [comment]
Hi @zuryx,

Many thanks for sharing the details here. Can you please let me know which architecture such as x86_64 are you running the JDK and Eclipse IDE on and whether you modified the domain.xml of domain1?

the `--add-opens` option will come into effect only when JDK version is greater than 9.
Also, can you please verify that the `JAVA_HOME` variable exists and points to the JDK 8 folder and not some other JDK version. 

`asadmin start-domain -v` should help you identify the JDK versions involved.

Let me know if this helps.
Warm regards
Deependra

**Comment by felixif** [comment]
Hello @zuryx,

We have updated the plugin since this issue was open. Do you still experience the same issues using the Eclipse plugin?
