### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by ojuschugh1** [payara/ecosystem-support#68]
### Brief Summary

Hi Everyone,
For the last few days, I was trying to run the Eclipse cargo-tracker application (maven project based on Jakarta EE 10 ) on Payara 6 server in Eclipse IDE. I was encountering the same error message every time, I try to run the application after starting the server of Payara 6 when I click on the run as on server option, It gives a Server Error message that the selection is not within the module.

On Investing the problem with fellow contributors I found that the Eclipse IDE does not support the new Jakarta EE 9/10 now, so the run as in the project context menu does not work.
​
The Link to repository-:https://github.com/OmniFish-EE/cargotracker/tree/omnifish-jee10

The steps to run the project on the local machine are provided in Readme.MD file.

Below I have attached the error message I am getting.

IDE-Eclipse ide for Enterprise Java and Web Developers.
Payara 6 server-Full Profile
JDK-17

Thanks and Regards

![error 4](https://github.com/payara/ecosystem-support/assets/79078267/d77b5b56-3005-4bc2-af16-35052aa26c37)

### Expected Outcome

Jakarta EE 10 project properly working on Payara 6 server using Eclipse IDE

### Current Outcome

Currently Jakarta EE 10 project is not properly working on Payara 6 server using Eclipse IDE

### Reproducer

Try the following steps to deploy manually.

mvn package -DskipTests to package the application into a war.
Run payara by asadmin start domain1
Copy the war to payara6\glassfish\domains\domain1\autodeploy

Thanks and Regards

### Operating System

Windows 10

### JDK Version

17

### Ecosystem Tool

Eclipse IDE Plugin

**Comment by Elifzeynepedman** [comment]
Hi @ojuschugh1,
 
I was able to successfully run this application with the latest version of Payara server (Payara Server 6.2023.7) on Eclipse. 
Would you please be able to test on the latest version.

Thank you,
Elif
