### ISSUE TITLE
Getting payara tools timeout exception when domain has secure admin enabled / FISH-1219

### ISSUE THREAD

**Issue by dkechrologos** [payara/ecosystem-support#7]
When I use payara tools in eclipse to start the server, the console starts logging messages and I am able to open a browser and login to the admin console. But after a while I get "Timeout while waiting for Payara to start"
This happens when the domain has secure admin enabled and i use password in properites page. If the domain doesn't have secure admin enabled and I don't enter any pass, it starts up ok. E.g. when trying default "domain1".

![image](https://user-images.githubusercontent.com/54798055/73617505-1d27b880-4628-11ea-9760-28f57900564e.png)

In eclipse log I am getting this:

!ENTRY org.eclipse.payara.tools 1 1 2020-02-03 01:52:27.639
!MESSAGE Payara: ServerStatusMonitor for Payara Server 5 (5.194) [dk.domains] location throws exception

**Comment by jGauravGupta** [comment]
Closing ticket as no more reproducible with the master branch, verified by @JamesHillyard & @jGauravGupta 

Verified in the following environments:
```
Windows 10
Eclipse Version: 2020-03
Java version "1.8.0_172"
Payara version 5.2020.5 / 5.2021.7
```
```
Windows 10
Eclipse Version: 2021-09
Java Version: 1.8.0_281
Payara Version: 5.2021.7
```
```
Ubuntu 20.04.2 LTS
Eclipse Version: 2020-12
Java Version: 1.8.0_282 (OpenJDK)
Payara Version: 5.2021.7
```
