### ISSUE TITLE
no longer works under IntelliJ 2023.2

### ISSUE THREAD

**Issue by StevenHachel** [payara/ecosystem-support#73]
### Brief Summary

Since the latest update, the payara plugin can no longer be used.
The message comes:
Incompatible: requires IDE build 231.* or earlier

IntelliJ IDEA 2023.2 (Ultimate Edition)
Build #IU-232.8660.185, built on July 26, 2023

### Expected Outcome

na

### Current Outcome

na

### Reproducer

na

### Operating System

Windows 10 Pro

### JDK Version

JDK 11

### Ecosystem Tool

IntelliJ IDEA IDE Plugin

**Comment by jGauravGupta** [comment]
Hi, Please install Payara Platform Tools 1.6.0 which is compatible with 2023.2.x.
