### ISSUE TITLE
Enhancement: please release Arquillian connectors 

### ISSUE THREAD

**Issue by lprimak** [payara/ecosystem-support#86]
### Brief Summary

Latest Payara 6 Arquillian connector needs to be released:

- please upgrade to Arquillian Core 1.8.0
- Release the latest 3.x version. 

This is needed for full TestContainers and docker support. Thank you!

### Expected Outcome

N/a

### Current Outcome

N/a

### Ecosystem Tool

Arquillian Connectors

**Comment by lprimak** [comment]
@jGauravGupta @abdulrahim458 please release me :)

**Comment by jGauravGupta** [comment]
Sure! Created internal ticket FISH-8561 to address it.

**Comment by lprimak** [comment]
This has been released!
